### ISSUE TITLE
The logstash would try reparse all the logs after each vagrant reload or host reboot

### ISSUE THREAD

**Issue by kamelzcs** [comperiosearch/vagrant-elk-box#12]
I put all the files under the shared folder `/vagrant`

`confs/logstash/logstash.conf ` is as below:
```
input {
  file {
    path => "/vagrant/project/http/access_log*"
    type => "apache_access"
    start_position => beginning
  }
}
```

I suspect the reason is each `vagrant reload` would remount the shared folder `/vagrant`, then the recorded `since_db*` could not find out that these files have been parsed, then it would try to parse them again.

Is any way to deal with it?

**Comment by sebnmuller** [comment]
Remove start_position => beginning, the default is end.
This will ensure only new changes to the file get picked up by logstash.

**Comment by kamelzcs** [comment]
Thanks for your info!

according to http://logstash.net/docs/1.4.2/inputs/file
`This option only modifies “first contact” situations where a file is new and not seen before. If a file has already been seen before, this option has no effect.`

The fact is one new log file is imported each day, then analyzed without problem.

Then after `vagrant reload`, it is reparsed again! `beginning` should not affect the behavour of the existing log file according to the docs.

Any ideas?

**Comment by UnrealQuester** [comment]
Putting the log file inside the box and not in /vagrant should cause the file to only be parsed once. You could also try to create a symlink inside the box that points to the log you want to parse and tell logstash to parse that symlink. Even if that works at all, that approach does not work for wildcards.

**Comment by babadofar** [comment]
This issue is now at https://github.com/elastic/logstash/issues/2890
