### ISSUE TITLE
Kibana is not workin

### ISSUE THREAD

**Issue by CingulateCortex** [comperiosearch/vagrant-elk-box#14]
Hi 

run vagrant up --provider=vmware_fusion 

successfully installed. however i could not make kibana working. Do we need extra config or so? 

thanks

**Comment by babadofar** [comment]
I never got around to writing an init script for Kibana, so it doesn't start automatically after your first install.  you can use this command 
`/vagrant/kibana/kibana-4.0.1-linux-x64/bin/kibana &`
to start up kibana in the background. 
Does that help you at all or are you experiencing some other problems?

**Comment by CingulateCortex** [comment]
i normally run bin file of kibana as you highlighted. but it listened 0.0.0.0:5651 

and application is not openning. do i need any extra service start?

**Comment by babadofar** [comment]
No, there is no other service, kibana is running it's own webserver. Still having problems?

**Comment by CingulateCortex** [comment]
yep when i try to run kibana manually, it says it is listening on 127.0.0.1:5651 but no webpage is opened.

**Comment by babadofar** [comment]
Shouldn't that be 127.0.0.1:5601
?

**Comment by CingulateCortex** [comment]
sorry that was typo, yes 127.0.0.1:5601 now workıng

**Comment by babadofar** [comment]
Great! Can we close this one now?

**Comment by CingulateCortex** [comment]
as i said, it is not working on 127.0.0.1:5601. actually initially it was 0.0.0.0:5601 which is coming from default image. changed it to localhost. still not working.

**Comment by babadofar** [comment]
try to log on to the vagrant box and issue a curl request. Like this
``` 
vagrant ssh
```
once logged in, enter 
```
curl http://localhost:5601
```
if you get "curl: (7) Failed to connect to localhost port 5601: Connection refused"
it means kibana isn't running. Then you need to start kibana manually, as explained on the readme on the frontpage, something like this, depending on your version:
```
/vagrant/kibana/kibana-4.0.2-linux-x64/bin/kibana &
```

Wait a few seconds, you will see a stream of messages on your screen, and then enter the curl command again. Now kibana should be running and you should get some html listed on your screen. If you still have problems, you need to supply some more details :).

**Comment by CingulateCortex** [comment]
I got curl response 
```
<!DOCTYPE html>
  <!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
  <!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" href="styles/theme/elk.ico">
    <title>Kibana 4</title>
    <link rel="stylesheet" href="styles/main.css?_b=5930">

  </head>
  <body kibana ng-class="'application-' + activeApp.id">

    <div class="row">
      <div class="col-md-offset-4 col-md-4 page-header initial-load">
        <center>
          <img width="128" src="images/initial_load.gif">
          <h1>
            <strong>Kibana</strong>
            <small id="cache-message">is loading. Give me a moment here. I'm loading a whole bunch of code. Don't worry, all this good stuff will be cached up for next time!</small>
          </h1>
        </center>
      </div>
    </div>

    <script>
      window.KIBANA_VERSION='4.0.1';
      window.KIBANA_BUILD_NUM='5930';
      window.KIBANA_COMMIT_SHA='0c88afd24c71ae4f8bb2dec3a26b7035440d36e3';
    </script>

    <script src="bower_components/requirejs/require.js?_b=5930"></script>
    <script src="require.config.js?_b=5930"></script>
    <script>
      var showCacheMessage = location.href.indexOf('?embed') < 0 && location.href.indexOf('&embed') < 0;
      if (!showCacheMessage) document.getElementById('cache-message').style.display = 'none';

      if (window.KIBANA_BUILD_NUM.substr(0, 2) !== '@@') {
        // only cache bust if this is really the build number
        require.config({ urlArgs: '_b=' + window.KIBANA_BUILD_NUM });
      }

      require(['kibana'], function (kibana) { kibana.init(); });
    </script>

  </body>
</html>
{"@timestamp":"2015-04-24T13:53:34.270Z","level":"info","message":"GET / 200 - 47ms","node_env":"production","request":{"method":"GET","url":"/","headers":{"user-agent":"curl/7.35.0","host":"127.0.0.1:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","remotePort":41368},"response":{"statusCode":200,"responseTime":47,"contentLength":1815}}
```
however when i try to reach from browser, getting web site not available error.

**Comment by babadofar** [comment]
that means kibana is working inside the box, but somehow can't communicate through to your host machine. Check your network. Do you have several network adapters? If vagrant couldn't forward ports, it would halt on startup. So it should be available.

**Comment by CingulateCortex** [comment]
nop vm fusion on OSX and guest machine which is ELK has eth0 and lo interfaces. even 127.0.0.1:5601 is unreachable. not trying to reach from host machine with regular IP address

**Comment by babadofar** [comment]
No warnings or errors during vagrant up? Can you access elasticsearch at 127.0.0.1:9200? 
You could try to set another remote port mapped to 5601 in the vagrantfile, perhaps.

**Comment by babadofar** [comment]
Any progress on this?
