### ISSUE TITLE
wget ubuntu.sh not idempotent

### ISSUE THREAD

**Issue by muelli** [comperiosearch/vagrant-elk-box#15]
I need to go trough an HTTP proxy and I have never dealt with puppet. So I need to try vagrant provision a few times. The vagrant provision script downloads ubuntu.sh from github.  after having done that several times,  I now have many ubuntu.sh.[123456] lying around.  I think this could easily be fixed with a `--continue` flag.

**Comment by babadofar** [comment]
The ubuntu.sh file is now added as part of the repository. That should close this issue :)
