### ISSUE TITLE
Ease setting up a box that needs to go through a proxy

### ISSUE THREAD

**Issue by muelli** [comperiosearch/vagrant-elk-box#16]
Currently, it seems to require an unsurmountable amount of effort to install an ELK-box which needs to go through a proxy. Even more so if that proxy requires authentication and intercepts HTTPS connections.

Firstly, `/usr/local/share/ca-certificates` needs to contain a `.crt` file. Then  `update-ca-certificates` needs to be run.
It may be required that
```
echo '
Defaults env_keep = "http_proxy https_proxy ftp_proxy DISPLAY XAUTHORITY"
'  >> /etc/sudoers
```
is run. 

`export http_proxy=...` is probably a good idea, too.

In order to use apt-get, 
```
proxies="
Acquire::http::proxy \\"$http_proxy\\";
Acquire::ftp::proxy \\"$http_proxy\\";
Acquire::https::proxy \\"$http_proxy\\";
"
echo "$proxies" > /etc/apt/apt.conf.d/88proxies
```
might be good.

that still doesn't make elasticsearch's apt-key command happy :-(

I expected it to be easier to configure a proxy for the system.

**Comment by babadofar** [comment]
I'm sorry that you have problems with proxies, they are known to inflict pain though. However, I don't think you should have any particular problems with using or installing elasticsearch behind a proxy. 
Once you get apt-get working I suspect you should be fine?

**Comment by muelli** [comment]
nope. Beside apt-get there is apt-key. And the mixture of the pre-puppet script that vagrant executes doesn't make things easier. And then there is the installation of the elastic search plugin. While that is yet another place where one can add a proxy (cf. https://forge.puppetlabs.com/elasticsearch/elasticsearch#using-a-proxy), it doesn't seem to be compatible with proxies which require authentication.  I manually (i.e. vagrant ssh) tested providing the `http_proxy{,s}` environment variable, but that didn't work.

**Comment by babadofar** [comment]
You should look into the issues at puppetlabs https://github.com/elastic/puppet-elasticsearch
https://github.com/elastic/puppet-elasticsearch/issues/152
Suggests adding auth for proxy like this ` proxy_host = 'user:pass@host'`

**Comment by babadofar** [comment]
I believe the problems are related to running behind a proxy, I'm not sure whether it's really a good idea to add support for proxy into this project. OK if we close the issue?

**Comment by muelli** [comment]
Depends on what you think should be the scope for this project.

I think every operation needs to appropriate environment. As a user, I'd appreciate if I only have to set a single variable instead of manipulating every statement in the puppet file. Especially as I don't know puppet, its classes and their arguments.

**Comment by babadofar** [comment]
If you want to go further with this, I suggest you either supply a pull request with changes needed for going through a proxy, or check out if there is something you can contribute to the elasticsearch puppet setup. Closing this issue
