### ISSUE TITLE
Ubuntu package repository unreachable

### ISSUE THREAD

**Issue by bramfoo** [comperiosearch/vagrant-elk-box#27]
Running Kubuntu 14.04.2, Vagrant 1.7.2 and VirtualBox 4.3.10, the `vagrant up` command fails because when it's trying to install/update packages in the VM, I get the following error:

`Err http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libgtk2.0-common all 2.24.23-0ubuntu1.1
==> default:   404  Not Found [IP: 91.189.91.13 80]`
(Not only for this package, but for quite  a few others)

This in turn leads to `Warning: /Stage[main]/Java::Config/Exec[update-java-alternatives]: Skipping because of failed dependencies` (and others), and finally the provisioning failing.

Not sure where to configure the Ubuntu repositories, any pointers would be appreciated.

**Comment by babadofar** [comment]
If you pull in latest changes and try again, it should use the ubuntu repo closest to your location.

**Comment by bramfoo** [comment]
Fantastic, that manages to retrieve the required packages and provision the machine successfully.
