### ISSUE TITLE
Register box on Atlas?

### ISSUE THREAD

**Issue by mewwts** [comperiosearch/vagrant-elk-box#30]
No results here: https://atlas.hashicorp.com/boxes/search?utf8=%E2%9C%93&sort=&provider=&q=vagrant-elk-box

**Comment by babadofar** [comment]
Probably a good idea. But how to do it?

**Comment by JaimeObregon** [comment]
Either [with Packer, via the Atlas web interface or the API](https://atlas.hashicorp.com/help/vagrant/boxes/create). Hope it helps.
