### ISSUE TITLE
SSH Auth

### ISSUE THREAD

**Issue by alexlanderWieland** [comperiosearch/vagrant-elk-box#31]
I am trying to get on the SSH, but i can't figure out what the password is.
Could someone help?

**Comment by babadofar** [comment]
just typing `vagrant ssh` in the folder where you have the Vagrantfile should bring you right in. If you're really curious `vagrant ssh-config` will show you how to connect.

**Comment by alexlanderWieland** [comment]
thank you. Was triying to connect via putty, my bad.
