### ISSUE TITLE
403 when connecting to Kibana

### ISSUE THREAD

**Issue by tbender** [comperiosearch/vagrant-elk-box#7]
When trying to connect to https://localhost:5601/ , I only get a 403 Forbidden from nginx. Did I miss something?

**Comment by ssoto** [comment]
Did you check the `/etc/nginx/sites-available/defaul` file?
What is your `/var/log/nginx/error.log` output?

**Comment by mewwts** [comment]
Shot oout of the blue, but have you tried: using ```http```?

**Comment by babadofar** [comment]
I think we can close this. Kibana 4 does not use nginx. Please file a new issue if there are still problems (but don't expect https to work).

**Comment by mewwts** [comment]
:+1:
