### ISSUE TITLE
VMFusion Usage

### ISSUE THREAD

**Issue by jchannon** [comperiosearch/vagrant-elk-box#9]
Will this work with the VMFusion Vagrant plugin?

**Comment by babadofar** [comment]
It hasn't been tested, but I suspect it might work. You may have to set another box,
 https://vagrantcloud.com/netsensia/boxes/ubuntu-trusty64 is used, there is configuration samples on 
https://docs.vagrantup.com/v2/providers/configuration.html if you should need to add a different one for VMFusion. Please test it, and report your success!

**Comment by jchannon** [comment]
I changed to that box but then came up against this: 
![screen shot 2015-02-26 at 13 00 05](https://cloud.githubusercontent.com/assets/105126/6392336/92619750-bdb7-11e4-8875-645c71435c4f.png)

**Comment by babadofar** [comment]
That's an error with the vagrant box. Should probably try another one, this one perhaps? 
https://atlas.hashicorp.com/phusion/boxes/ubuntu-14.04-amd64

**Comment by jchannon** [comment]
I did try this but it had a linux header error because of guest addtions not being installed, ill try the other one you recommended

**Comment by jchannon** [comment]
The one you recommended seems much better however once kibana is downloaded I get a LOT of `Cannot change ownership to uid 503, gid 50: Operation not permitted` warnings

**Comment by jchannon** [comment]
looks like using `sudo vagrant` did the trick

**Comment by babadofar** [comment]
Great! Feel free to submt a pull request :)

2015-02-26 16:39 GMT+01:00 Jonathan Channon <notifications@github.com>:

**Comment by jchannon** [comment]
Will do. Just need to learn how to use kibana now. Doesn't seem to
intuitive
